language: en
debug: false
regenfix: false
autodownload: true
installondownload: false
internet: true
UsePrefix: true
PrefixColor: b
TextColor: 6
enableingameandsql: true
showcommandsonconsole: true
allfile: true
all: true
playerxy: true