language: en
debug: false
regenfix: false
autodownload: true
installondownload: false
internet: true
UsePrefix: true
PrefixColor: b
TextColor: 6
enableingameandsql: true
showcommandsonconsole: true
liteSQLdata: false
maxLookupRadius: 20
maxElementsPerQuery: 45
CleanUPAfter: 4w
permissions:
  error:
    de: Wir haben ein Problem! Dies darfst Du nicht machen!
    en: we have a problem! You musnt do this!
  notfound:
    de: PermissionsEx plugin nicht gefunden!
    en: PermissionsEx not found!
allfile: true
all: true
playerxy: true