name:  CommandLogger
version:  0.5
description:  
author:  ibhh
website: http://www.ibhh.de/CommandLogger

main: me.ibhh.CommandLogger.CommandLogger

commands:
  CommandLogger:
    description: 
    usage: /CommandLogger
permissions:
  CommandLogger.*:
    description: None
    children:
      CommandLogger.download: false
    description: Downloads new Version.
    default: false
  CommandLogger.download:
    description: Downloads new Version.
    default: false